# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - identifier_name
  - type_name
  - weak_delegate
  - class_delegate_protocol
  - nesting
  - implicit_getter
  - valid_ibinspectable
  - force_cast
  - force_try
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count # Find all the available rules by running: `swiftlint rules`

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length:
    warning: 200
    ignores_comments: true
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
function_body_length:
  warning: 80
  error: 100
function_parameter_count:
  warning: 6
  error: 7
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
